language: python

python:
  - 3.7

install:
  - pip install -r requirements.txt
  - make build

env:
  - DJANGO_SETTINGS_MODULE="ebdjango2.settings"

before_script:
  - python manage.py migrate
  - python manage.py collectstatic --noinput

script:
  - black --check .
  - flake8 .
  - coverage run --source=mysite,polls manage.py test

after_script:
  - coveralls
