language: python

python:
  - 3.7

install:
  - pip install -r requirements.txt

env:
  - DJANGO_SETTINGS_MODULE="ebdjango2.settings"

before_script:
  - chmod +x ./manage.py
  - python manage.py migrate


script:
  - python manage.py test

after_script:
  - coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "AKIAX2OILUITPJRS63N5"
  secret_access_key:
    secure: "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"
  region: "us-east-1"
  app: "ebdjango2"
  env: "django-env"
  bucket_name: "elasticbeanstalk-us-east-1-537827975718"
  on:
   branch: main

