language: python

python:
  - 3.7

install:
  - pip install -r requirements.txt

env:
  - DJANGO_SETTINGS_MODULE="ebdjango2.settings"

before_script:
  - chmod +x ./manage.py
  - python manage.py migrate
  - python manage.py collectstatic --noinput


script:
  - python manage.py test

after_script:
  - coveralls
